/**
 * Renders a URL to PDF using headless Chromium via Playwright.
 * Invoked as a child process by the OBV server (POST /api/reports/generate):
 *
 *   node scripts/render-pdf.js <base64-json-config>
 *
 * config: { url, outPath, projectName, generatedAt }
 *
 * Playwright is a pinned DEV dependency of this repository (see
 * scripts/lib/browser.js); the application itself still has zero runtime
 * dependencies. When Playwright or its Chromium build is absent the
 * server falls back to printable HTML.
 */
const { launchChromium } = require("./lib/browser");

const config = JSON.parse(Buffer.from(process.argv[2], "base64").toString("utf8"));

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const footerTemplate = `
  <div style="width:100%;font-size:7px;color:#5b6b7f;font-family:Arial,sans-serif;
              padding:0 12mm;display:flex;justify-content:space-between;align-items:baseline">
    <span>OpenBuild Verify &middot; ${esc(config.projectName)}</span>
    <span>${esc(config.generatedAt)}</span>
    <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span> &middot; Generated by OBV Demo Environment</span>
  </div>`;

(async () => {
  const browser = await launchChromium({ args: ["--no-sandbox"] });
  try {
    const page = await browser.newPage();
    await page.goto(config.url, { waitUntil: "networkidle", timeout: 30000 });
    await page.pdf({
      path: config.outPath,
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<span></span>",
      footerTemplate,
      margin: { top: "13mm", bottom: "17mm", left: "12mm", right: "12mm" },
    });
    console.log("PDF written:", config.outPath);
  } finally {
    await browser.close();
  }
})().catch((err) => {
  console.error("PDF render failed:", err.message);
  process.exit(1);
});
